spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/umc7th
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

Jwt:
  secret: ${JWT_SECRET}
  token:
    access-expiration-time: 3600000 # Milliseconds for 1 hour
    refresh-expiration-time: 2592000000 # Milliseconds for 30 days