spring:
  datasource:
    username: youngjaeRo
    password: "Shdudwo4469%%"
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

Jwt:
  secret: ${JWT_SECRET}
  token:
    access-expiration-time: 3600000 # Milliseconds for 1 hour
    refresh-expiration-time: 2592000000 # Milliseconds for 30 days

  # OAuth2 login
  security:
    oauth2:
      client:
        registration:
          kakao:
            authorization-grant-type: authorization_code
            client-id: 22163373cf5902dbfa44bc74a921208b
            redirect-uri: http://localhost:8080/oauth2/callback/kakao
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - profile_image
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


springdoc:
  swagger-ui:
    path: /