spring:
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8084  # 서버 포트 설정

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect   # MySQL 8.x에 맞는 Dialect 추가
        format_sql: true


#localhost:8080/하면 swagger실행
springdoc:
  swagger-ui:
    path: /


Jwt:
  secret: ${JWT_SECRET}
  token:
    access-expiration-time: 3600000 # Milliseconds for 1 hour
    refresh-expiration-time: 2592000000 # Milliseconds for 30 days