spring:
  datasource:
    username: root
    password: '0404'
    url: jdbc:mysql://localhost:3306/umc
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

springdoc:
  swagger-ui:
    path: /

Jwt:
  secret: ${JWT_SECRET}
  token:
    access-expiration-time: 3600000 # Milliseconds for 1 hour
    refresh-expiration-time: 2592000000 # Milliseconds for 30 days